### ISSUE TITLE
Support for adding custom image name

### ISSUE THREAD

**Issue by qi-zhou** [theplant/plantbuild#14]
Currently, when use planbuild on dev environment, Image name will be automatically generated based on k8s namespace and app name，sometimes this path does not exist image：

For example：

- namespace：aigle-dev
- appName： admin
- imageName = "registry.theplant-dev.com/" + "aigle-dev" + "/" + "admin"
- imageTag"gitCommitHash" 

But what `imageName` we need is `registry.theplant-dev.com/aigle/admin`, So we need can set `imageName`, and imageTag default is `gitCommitHash`

**Comment by sunfmin** [comment]
This is fixed with https://github.com/theplant/plantbuild/commit/3cee87eca83a6d374b74d024cf9131d233599372
