### ISSUE TITLE
Support multiple containers in one deployment

### ISSUE THREAD

**Issue by idealhack** [theplant/plantbuild#3]
It seems that multiple functions need to be changed to support this...

I felt it would be nicer if we implement the k8s part in Go if we are going to have more requirements like this.

Also, I'm having problems running `test.sh`.

```
./test.sh: line 27: syntax error near unexpected token `('
./test.sh: line 27: `        if diff -B <(printf "$actual\n") <(printf "$expected\n"); then'
```

**Comment by idealhack** [comment]
I could use some help here @sunfmin 😄

**Comment by idealhack** [comment]
You are right, I tried `zsh` and `sh` but not `bash`.

Here's a PR to add docs about this #4

**Comment by sunfmin** [comment]
I wonder why this on top of the script didn't work

```
#!/bin/bash

subcommand=$1
shift
```

**Comment by sunfmin** [comment]
https://stackoverflow.com/questions/15944859/error-syntax-error-near-unexpected-token-when-add-diff-command-in-shell-s

Learned something new: http://tldp.org/LDP/abs/html/process-sub.html

**Comment by idealhack** [comment]
I'm going to close this for now as theplant/internal#748 was closed.

Feel free to reopen if this still relevant.
